### ISSUE TITLE
Support Linux

### ISSUE THREAD

**Issue by Salzian** [Salzian/bevy_fmod#3]

**Comment by GitGhillie** [comment]
If I put the API library files in target/debug/deps all the examples work, but if I put those in the root folder it cannot find them. Not sure if there is a better way

**Comment by passivedragon** [comment]
what files exactly are missing?
I just tried to build an example and encountered:
```txt
/usr/bin/ld: cannot find -lfmodstudio: No such file or directory
/usr/bin/ld: cannot find -lfmod: No such file or directory
collect2: error: ld returned 1 exit status
```
which I presume is the same issue you found. I'm not sure where these should be coming from.

Is this an issue inherited from libfmod? Which files are missing?

**Comment by GitGhillie** [comment]
@passivedragon just to make sure we are on the same page here, it _does_ work if you follow the following instructions:

1. Go to https://fmod.com/download#fmodengine and download the Linux one. 
2. Take all the files from `api/core/lib/<platform>` and `api/studio/lib/<platform>`
3. Put them in the `target/debug/deps` folder of your Bevy project.

The issue is just that it's not very ergonomic to put the library files inside the target folder, as that folder is generated when you build your Bevy project, and deleted when you run something like `cargo clean`. But indeed I get those same errors when I place the files in the Bevy project root for example.

Not sure yet if it's a libfmod issue, I'm a noob when it comes to linking. I will check if there is a way to contact the author

**Comment by Salzian** [comment]
I had the same issue trying out the project on MacOS. 

To my understanding, it's not a libfmod issue. Dynamic libraries in general are linked differently by Rust on Windows, MacOS and Linux.

On Windows, it's sufficient to put the DLLs during development into the root of the repository. 

I did some trials with copying the libs during build time, but other issues took priority first.

**Comment by GitGhillie** [comment]
I got it working by doing the following in my project:

1. Put the files (see https://github.com/Salzian/bevy_fmod/issues/3#issuecomment-1735908054) in `/usr/lib/x86_64-linux-gnu/fmod-api/`
2. Add a build.rs
3. Add `println!("cargo:rustc-link-search=/usr/lib/x86_64-linux-gnu/fmod-api/");`
4. Add `println!("cargo:rustc-env=LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/fmod-api/");`

There is probably a better way but I think this is method is somewhat in the direction you would take when shipping your game. The only downside is that this breaks the Bevy dynamic_linking feature.

**Comment by Salzian** [comment]
I'm glad to see this working for Linux. I remember looking into a very similar approach for macOS, but the linker (I guess) didn't pick up the added options.

If your approach is a reliable fix for Linux, feel free to open a PR.

Please make sure to test this in a separate application first. I would like to know what the behavior of the `build.rs` is for dependencies.

Also, can you elaborate how this breaks dynamic_linking? Does the application not find the bevy libs anymore?

**Comment by GitGhillie** [comment]
I'm not familiar with how dynamic_linking exactly works but I get this error if I enable it:
```
target/debug/fmod-showcase: error while loading shared libraries: libbevy_dylib-0a701fc45ca5169a.so: cannot open shared object file: No such file or directory
```
I will open a PR and add a warning about this for the time being.
